### ISSUE TITLE
Uploading code?

### ISSUE THREAD

**Issue by ariel415el** [EzioBy/glead#1]
Hi, 
Are you intending to upload your code ?

**Comment by EzioBy** [comment]
Yes. Code will be released and please stay tuned.

**Comment by anandbhattad** [comment]
What is the expected timeline for code release and pretrained models?

**Comment by Nikolai10** [comment]
@EzioBy: any updates here?

**Comment by EzioBy** [comment]
Thanks for your attention and patience.
The releasing of the code involves the property rights of the company and the security review process is in progress currently.
Hopefully the code will be released in the next two weeks.

**Comment by Alaa-Arbi** [comment]
@EzioBy, could you please share an approximate date for the code release ? for planning reasons

**Comment by EzioBy** [comment]
Hi Alaa-Arbi, the security check has passed and our code is planned to be released next week.

**Comment by EzioBy** [comment]
Hello everyone @ariel415el @anandbhattad @Nikolai10 @Alaa-Arbi, the code and pre-trained models have been released. Hope it can be of some use to you.

**Comment by Nikolai10** [comment]
> Hello everyone @ariel415el @anandbhattad @Nikolai10 @Alaa-Arbi, the code and pre-trained models have been released. Hope it can be of some use to you.

Great to hear, thank you!
