### ISSUE TITLE
Default settings for training (combination with GGDR)

### ISSUE THREAD

**Issue by hse1032** [EzioBy/glead#3]
Hello,

Default settings in the "train_scripts_*.py" uses reg_target_fake as 'gfeat' and reg_target_real as 'gfwimage'.
In this setting means the combination of glead and ggdr? (* in Table 1.)

Thanks,

**Comment by EzioBy** [comment]
Yes. Under this setting, D is required to match the generated features when discriminating fake imgaes and extract representative features for reconstruction when discriminating real imgaes. Set the option 'reg_target_fake' to 'gfwimage' if you would like to try another setting.

**Comment by hse1032** [comment]
Thanks for your reply.
